---
- name: Install packages for RedHat
  yum: name={{ item }} state=present
  with_items:
    - autoconf
    - bison
    - flex
    - gcc
    - gcc-c++
    - kernel-devel
    - make
    - m4
    - patch
    - ncurses-devel
    - git
    - openssl-devel
    - zlib-devel
    - readline-devel
    - libxml2-devel
    - libxslt-devel

